version: 2.1

orbs:
  node: circleci/node@7.0.0

parameters:
  node_version:
    type: string
    default: '22.12.0'

jobs:
  publish:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            VERSION=$(node -p "require('./package.json').version")
            npm info @shelf/esbuild-config@$VERSION > /dev/null 2>&1 || npm publish

workflows:
  tagged-build:
    jobs:
      - publish:
          context: npm-write
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
